version: '3.1'

services:

  db_estoque:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: estoque
      POSTGRES_DB: estoque
    ports:
      - 5402:5432
    volumes:
      - db_estoque:/var/lib/postgresql/data
    
volumes:
  db_estoque: